FROM pytorch/pytorch:2.4.0-cuda11.8-cudnn9-runtime
USER root
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN mkdir -p /app/Prospecting
WORKDIR /app/Prospecting

RUN apt-get update && apt-get install -y \
    zip \
    unzip \
    git \
    curl \
    tmux \
    valgrind \
    libssl-dev \
    pkg-config \
    htop \
    wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#gccのインストール
RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    --fix-missing \
    && rm -rf /var/lib/apt/lists/*



# TA-Libのビルドとインストール
RUN wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz && \
    tar -xzf ta-lib-0.4.0-src.tar.gz && \
    cd ta-lib && \
    ./configure --prefix=/usr && \
    make && \
    make install && \
    cd .. && \
    rm -rf ta-lib ta-lib-0.4.0-src.tar.gz


RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python3 - && \
ln -s /opt/poetry/bin/poetry /usr/local/bin/poetry



